name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/python:3.12

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      run: |
        curl -sSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"

    - name: Run tests
      run: |
        python -m pytest --cov=blokus_duo

    - name: Run ruff
      run: |
        ruff check .

    - name: Run pyright
      run: |
        python -m pip install pyright
        pyright

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false

  build-devcontainer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build devcontainer
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/username/blokus-devcontainer
        push: never
